export const SET_PLAYING_START = 'SET_PLAYING_START'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_LOVE_SONG = 'SET_LOVE_SONG'

export const SET_USER_INFO ='SET_USER_INFO'

export const SET_USER_INFO_DETAIL = 'SET_USER_INFO_DETAIL'
